algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
 black_friday: logico // verdadeiro ou falso
inicio
// Seção de Comandos 

 // processamento de variaveis e constantes
 
 black_friday <- falso
 
 // se blackfriday NÃO é verdadeira
 se nao(black_friday) entao
   escreva("não estamos na black friday")
   
 senao
   escreva("estamos na black friday :D")
 
 fimse
fimalgoritmo
