Algoritmo "semnome"

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2022
Var
// Seção de Declarações das variáveis 
  idade: inteiro
  

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

 escreva("escreva sua idade ")
 leia(idade)


 // decisão/condicional

 se(idade >= 18) e (idade < 60) entao
   escreva("adulto")
 senao
   se(idade >= 60) entao
    escreva("idoso")
   
   senao
  
    escreva("menor")
   fimse
 fimse

Fimalgoritmo