algoritmo "semnome"
// Função : obter verificação de idade e verificar se é adulto
// Autor :  Matheus
// Data : 17/02/2022
// Seção de Declarações 
var
 // declaração de variaveis
 idade: inteiro

inicio
// Seção de Comandos

 escreva("informe sua idade: ")
 leia(idade)
 
 // estrutura condicional simples
 
 se (idade >= 18) entao
  escreval("voce é maior de idade")
  fimse
  
  escreval("o programa segue fazendo outras coisas...")
fimalgoritmo
