algoritmo "semnome"
// Função : exibir os dados de usuario na tela depois
// que o mesmo digitou elas anteriormente
// Autor : Matheus Anthony
// Data : 17/02/2022
// Seção de Declarações 
var
 nome: caractere
 idade: inteiro


inicio
// Seção de Comandos 


 escreva("Digite aqui o seu nome: ")
 leia(nome)
 
 escreva("Digite aqui a sua idade: ")
 leia(idade)
 
 //saida
 escreval("Seu nome é: ", nome)
 escreval("Sua idade é: ", idade, " anos")
fimalgoritmo
