algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2022
// Seção de Declarações 
var
filmes: vetor[1..5] de caractere
posicao: inteiro
inicio
// Seção de Comandos

para posicao de 1 ate 5 faca
escreva("informe o nome do ", posicao, "° filme: ")
leia(filmes[posicao])

fimpara

limpatela
//saida

para posicao de 1 ate 5 faca
escreva(posicao,"° ")
escreval(filmes[posicao])

fimpara
fimalgoritmo
