algoritmo "semnome"
// Função :
// Autor :
// Data : 04/03/2022
// Seção de Declarações 
var
 contador: inteiro
 nome_artista: caractere
 contador_numeral: inteiro

inicio
// Seção de Comandos 
  para contador de 1 ate 5 faca
  
  escreva("Informe o nome do/a",contador, "° artista: ")
  leia(nome_artista)

// saida

escreval()
escreval("nome do/a artista: ", nome_artista)
escreval()
fimpara
fimalgoritmo
